/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generarfoliosbienevale;

import java.awt.Color;
import java.awt.FileDialog;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Anthony Tepach
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Repo_BD = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jtf_ruta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_iniciaen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_folini = new javax.swing.JTextField();
        jtf_folfin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jrb_impresion = new javax.swing.JRadioButton();
        jrb_repos = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jtf_vigencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_serie = new javax.swing.JTextField();
        generar = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Guardar como..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtf_ruta.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Inicia en:");

        jtf_iniciaen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_iniciaen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_iniciaenKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Folio inicial:");

        jtf_folini.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_folini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_foliniKeyTyped(evt);
            }
        });

        jtf_folfin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_folfin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_folfinKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Folio final:");

        Repo_BD.add(jrb_impresion);
        jrb_impresion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrb_impresion.setSelected(true);
        jrb_impresion.setText("Base para impresión");

        Repo_BD.add(jrb_repos);
        jrb_repos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jrb_repos.setText("Base para Repos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Vigencia:");

        jtf_vigencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_vigencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_vigenciaKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Serie:");

        jtf_serie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_serie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_serieKeyTyped(evt);
            }
        });

        generar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generar.setText("Generar");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtf_iniciaen)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtf_vigencia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtf_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_folini))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_folfin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb_impresion)
                                    .addComponent(jrb_repos)))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_folfin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_folini, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_iniciaen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrb_impresion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrb_repos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_vigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtf_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generar))
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jProgressBar1.setBackground(new java.awt.Color(51, 51, 51));
        jProgressBar1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBar1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtf_ruta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jtf_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FileDialog dialogoArchivo;
        dialogoArchivo = new FileDialog(this, "Guardar como...", FileDialog.SAVE);
        dialogoArchivo.setVisible(true);
        String ruta = dialogoArchivo.getDirectory() + dialogoArchivo.getFile() + ".txt";
        jtf_ruta.setText(ruta);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtf_iniciaenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_iniciaenKeyTyped
        charTypeInt(evt);
        limitar(jtf_iniciaen, 4, evt);
    }//GEN-LAST:event_jtf_iniciaenKeyTyped

    private void jtf_foliniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_foliniKeyTyped
        // TODO add your handling code here:
        charTypeInt(evt);
        limitar(jtf_folini, 9, evt);
    }//GEN-LAST:event_jtf_foliniKeyTyped

    private void jtf_folfinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_folfinKeyTyped
        // TODO add your handling code here:
        charTypeInt(evt);
        limitar(jtf_folfin, 9, evt);
    }//GEN-LAST:event_jtf_folfinKeyTyped

    private void jtf_vigenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_vigenciaKeyTyped
        // TODO add your handling code here:
        charTypeInt(evt);
        limitar(jtf_vigencia, 4, evt);
    }//GEN-LAST:event_jtf_vigenciaKeyTyped

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here
        GenerarFoliosBienevale gfb = new GenerarFoliosBienevale();
        if (!jtf_ruta.getText().isEmpty()) {
            if (camposvacios()) {
                HashMap data = new HashMap<String, String>();
                if (jtf_folini.getText().length() == 9 && jtf_folfin.getText().length() == 9) {
                    data.put("fol_ini", jtf_folini.getText());
                    data.put("fol_fin", jtf_folfin.getText());
                } else {
                    JOptionPane.showMessageDialog(rootPane, "El folio debe de ser de 9 Digitos contando en número de la zona", "Error", JOptionPane.ERROR_MESSAGE);
                }

                data.put("ruta", jtf_ruta.getText());
                data.put("vigencia", jtf_vigencia.getText());
                data.put("serie", jtf_serie.getText());
                data.put("inicia_en", jtf_iniciaen.getText());
                if (jrb_impresion.isSelected()) {
                    System.out.println("impresion");
                    generar.disable();
                    new Thread() {
                        public void run() {
                            gfb.paraImpresion(data, rootPane);
                            iniciarCarga();
                            musarCarga();
                            
                        }
                    }.start();
                    generar.enable();
                } else if (jrb_repos.isSelected()) {
                    System.out.println("repos");
                    generar.disable();
                     new Thread() {
                        public void run() {
                            gfb.paraRepos(data, rootPane);
                            iniciarCarga();
                            musarCarga();
                            }
                    }.start();
                    generar.enable();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Ingresa todos los campos para continuar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecciona la ruta de guardado para continuar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generarActionPerformed

    private void jtf_serieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_serieKeyTyped
        limitar(jtf_serie, 5, evt);
        char charecter = evt.getKeyChar();
        if (Character.isLowerCase(charecter)) {
            evt.setKeyChar(Character.toUpperCase(charecter));
        }
    }//GEN-LAST:event_jtf_serieKeyTyped

    private void jProgressBar1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBar1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBar1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Repo_BD;
    private javax.swing.JButton generar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jrb_impresion;
    private javax.swing.JRadioButton jrb_repos;
    private javax.swing.JTextField jtf_folfin;
    private javax.swing.JTextField jtf_folini;
    private javax.swing.JTextField jtf_iniciaen;
    private javax.swing.JTextField jtf_ruta;
    private javax.swing.JTextField jtf_serie;
    private javax.swing.JTextField jtf_vigencia;
    // End of variables declaration//GEN-END:variables
private void charTypeString(java.awt.event.KeyEvent ke) {
        char c = ke.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            ke.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se acceptan letras en este campo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void charTypeInt(java.awt.event.KeyEvent ke) {
        char c = ke.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            ke.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se acceptan números en este campo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    void iniciarCarga() {
        new Thread() {
            public void run() {
                int a = 0;
                double s = 0;
                while (a <= 101 && s <= 101) {
                    s += 0.30;
                    a += s;
                    jProgressBar1.setValue(a);
                    try {
                        sleep(100);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        }.start();
    }

    void musarCarga() {
        progreso().setBackground(Color.red);
        progreso().setForeground(new Color(0, 0, 0));
        progreso().setStringPainted(true);
    }

    public javax.swing.JProgressBar progreso() {
        return jProgressBar1;
    }

    private void limitar(JTextField caja, int limite, java.awt.event.KeyEvent ke) {
        if (caja.getText().length() == limite) {
            ke.consume();
        }
    }

    private boolean camposvacios() {
        boolean a;
        a = !(jtf_folfin.getText().isEmpty() && jtf_folini.getText().isEmpty() && jtf_iniciaen.getText().isEmpty() && jtf_serie.getText().isEmpty() && jtf_vigencia.getText().isEmpty());
        return a;
    }
}
